### ISSUE TITLE
Test count is incorrect

### ISSUE THREAD

**Issue by 0x8890** [scottcorgan/tap-dot#7]
Given this input:
```
TAP version 13
ok 1 a
ok 2 b
ok 3 c
ok 4 d
ok 5 e
1..5
# all tests passed
# test finished in 0.055 s
```
I got this output:
```
  .....

  2 tests
  5 passed

  Pass!
```
The count is showing the number of comment lines. This is a problem with `v1.0.1`, but not `v1.0.0`.

**Comment by scottcorgan** [comment]
Bummer! I have a release, `2.0.0`, planned for the next few days. It's a complete rewrite of `tap-dot` that's more stable and faster. This will all be fixed in that release.

If you'd like to open a PR until then, I'd love to merge it and release it ASAP!

**Comment by waylonflinn** [comment]
Ran into the same thing when including extra diagnostic information in the test cases. Number of tests is over-reported instead of under-reported in that case.

example TAP output looks like this:

```
# This is diagnostic output
# More diagnostic output for troubleshooting purposes.
TAP version 13
# real test #1
ok 1 should be equal
# real test #2
ok 2 should be equal
# real test #3
ok 3 should be equal
# real test #4
ok 4 should be equal
# real test #5
ok 5 should be equal
# real test #6
ok 6 should be equal
# real test #7
ok 7 should be equal
# real test #8
ok 8 should be equal

1..8
# tests 8
# pass  8

# ok
```

Gives output like
```
........  

  10 tests
  8  passed
  
  Pass!
```

Great library, sounds like you're working on the fix. Just wanted to make sure this edge case was included. Thanks!

**Comment by scottcorgan** [comment]
It is true, I am working on it. I have been working on a collection of packages under the org [tap-format](https://github.com/tap-format) as sequels to my few [tap-[formatter]](https://github.com/search?utf8=%E2%9C%93&q=repo%3Ascottcorgan%2Ftap-spec+repo%3Ascottcorgan%2Ftap-dot+repo%3Ascottcorgan%2Ftap-out&type=Repositories&ref=searchresults) modules.

https://github.com/tap-format/dot will be the replacement for this. It's basically done, just needs documentation and screenshots/video-gifs.

**Comment by 0x8890** [comment]
Great, closing this issue then. Maybe you can also mark this package as deprecated?

**Comment by scottcorgan** [comment]
It's not deprecated yet, but soon.
